### ISSUE TITLE
Upgrade Elasticsearch 

### ISSUE THREAD

**Issue by mausch** [ypereirareis/vagrant-elasticsearch-cluster#18]
This box is using an old version of Elasticsearch. I want to upgrade to 1.4.2 and Java 8.
How do I fork https://vagrantcloud.com/ypereirareis/boxes/debian-elasticsearch-amd64 and do these upgrades?

Thanks

**Comment by ypereirareis** [comment]
Hi ! I'm doing the upgrade right now.... Wait for a few hours and you'll be able to use ES 1.4.3

**Comment by ypereirareis** [comment]
@mausch The upgrade is done for the repo and the vagrant base box.
Next time you wanna upgrade the box you should follow these instructions:

* Get the base box on your local machine with `CLUSTER_COUNT=1 vagrant up --no-provision`
* Log into the launched VM with `vagrant ssh`
* Update lib/upgrade.sh script with the desired version of ES and plugins.
* Execute the new version of this script `/vagrant/lib/upgrade.sh` to install everything in the box.
* Package a new box `vagrant package --output="VAGRANT_BOX_NAME.box"`
* Change your Vagrantfile to use this new packaged box.

And then, you will be able to use the cluster with the new versions of applications.

**Comment by mausch** [comment]
Perfect, thanks!

**Comment by denis-chmel** [comment]
Really helpful, grand merci!
